brands/urls.py
from django.urls import path
from . import views

app_name = 'brand_portal'

urlpatterns = [
    path('brand/', views.BrandPortalView.as_view(), name='brand_portal'),
    path('download/<str:model_name>/<int:pk>/',
         views.download_file, name='download_file'),
    path('view-catalogue/<int:catalogue_id>/',
         views.view_catalogue, name='view_catalogue'),

]

contact/urls.py
from django.urls import path
from .views import index, home_view, validate_phone_api, footer_email_submit

app_name = 'contact'

urlpatterns = [
    path('contact/', index, name='contact'),
    path('validate-phone/', validate_phone_api, name='validate_phone'),
    path("", home_view, name='home'),
    path('footer/submit/', footer_email_submit, name='footer_email_submit'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.http import HttpResponse
from django.contrib.sitemaps.views import sitemap
from core.sitemaps import sitemaps
from django.shortcuts import redirect



def robots_txt(request):
    lines = [
        "User-agent: *",
        "Disallow: /admin/",
        "Disallow: /api/",
        "Disallow: /media/private/",
        "Disallow: /i18n/setlang/",
        "",
        "Sitemap: https://tomoil.de/sitemap.xml"
        
    ]
    return HttpResponse('\n'.join(lines), content_type="text/plain")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', robots_txt),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),

]

urlpatterns += i18n_patterns(
    path('', include("caseStudies.urls")),
    path('', include("questions.urls")),
    path('', include("contact.urls")),
    path('', include("news.urls")),
    path('', include("brands.urls")),
    path('', include("services.urls")),
    path('', include("whoweare.urls")),
    path('', include("products.urls")),
    path('', include("search.urls")),

    prefix_default_language=False
)

urlpatterns += [
    re_path(r'^rosetta/', include('rosetta.urls'))
]

urlpatterns += [
    re_path(r'^en/(?P<path>.*)$', lambda request, path: redirect(f'/{path}', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'contact.views.custom_404_view'
handler500 = 'contact.views.custom_500_view'
handler403 = 'contact.views.custom_403_view'
handler503 = 'contact.views.custom_503_view'


# Error URLs redirects
error_urls = {
    'pds_sds/': 'pds-sds/',
    'our_commitment/': 'our-commitment/',
    'vision_mission/': 'vision-mission/',
    'fr/news/0/': 'fr/news/',
    'services/marketing/': 'services/',
    'products/motor-oil-for-truck-and-buses/': '',
    'de/news/0/': 'de/news/',
    'zh-hans/news/0/': 'zh-hans/news/',
    'es/news/0/': 'es/news/',
    'services/industry/': 'services/',
    'news/0/': 'news/',
    'products/adblue/': 'products/',
    'products/gear-oils-and-transmission-fluids/': 'products/',
    'products/antifreeze-and-coolants/': 'products/',
    'products/break-fluid/': 'products/',
    'services/fleet/': 'services/',
    'company/vision-mission/': 'vision-mission/',
    'products/industrial-oils/': '?product_range=industrial-gear-oil',
    'company/culture/': '',
    'cdn-cgi/l/email-protection/': '',
    'static/tomoil-motoroil.pdf/': '',
}

for old_slug, new_slug in error_urls.items():
    urlpatterns += [
        path(f'{old_slug}', lambda request, new_slug=new_slug: redirect(f'/{new_slug}', permanent=True))
    ]

news/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'news'

urlpatterns = [
    path('news/', views.news_list, name='news_list'),
    path('api/news/', views.news_api, name='news_api'),
    path('news/<slug:slug>/', views.news_detail, name='news_detail'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

search/urls.py
from django.urls import path
from . import views 

app_name = 'search'

urlpatterns = [
    path('search/', views.search_view, name='search'),
]

pageheader/models.py
from django.db import models


class PageHeader(models.Model):
    page_key = models.CharField(
        max_length=100,
        unique=True,
        help_text="Unique identifier for this page (e.g., 'news_list', 'case_studies')"
    )
    breadcrumb_title = models.CharField(
        max_length=100,
        help_text="Title for the breadcrumb link"
    )
    breadcrumb_url = models.CharField(
        max_length=200,
        help_text="URL for the breadcrumb link"
    )
    page_title = models.CharField(
        max_length=200,
        help_text="Main title displayed in the header"
    )
    page_description = models.TextField(
        help_text="Description text displayed below the title",
        blank=True,
        null=True
    )
    background_image = models.ImageField(
        upload_to='page_headers/',
        null=True,
        blank=True,
        help_text="Background image for the header"
    )

    def __str__(self):
        return f"{self.page_key}: {self.page_title}"

    class Meta:
        verbose_name = "Page Header"
        verbose_name_plural = "Page Headers"

pageheader/views.py
from django.shortcuts import render

# Create your views here.

templates/components/footer.html
{% load static %} {% load i18n %}

<footer class="site-footer">
  <div class="footer-container">
    <div class="footer-col footer-brand">
      <div class="footer-logo">
        <img loading="lazy" src="{% static 'images/LOGOWHITE.png' %}" alt="Tomoil" />
      </div>
      <p class="footer-description">
        {% blocktrans %} Corporate business typically refers to large-scale
        mansola it enterprises or organizat {% endblocktrans %}
      </p>
      <div class="social-icons">
        <a href="https://www.facebook.com/people/Tomoil/61576825467224/" class="social-icon" target="_blank"
          aria-label="Link To Facebook"><i class="fab fa-facebook-f"></i></a>
        <a href="https://www.instagram.com/tomoil.de/" class="social-icon" target="_blank" aria-label="Link To Instagram"><i
            class="fab fa-instagram"></i></a>
        <a href="https://www.youtube.com/@TomoilLubricants" class="social-icon" target="_blank"  aria-label="Link To Youtube">
          <i class="fab fa-youtube"></i></a> 
        <!-- <a href="#" class="social-icon"><i class="fab fa-tiktok"></i></a> -->
        <a href="https://www.linkedin.com/company/tomoil-lubricants-auto-chemicals/" class="social-icon"
          aria-label="Link To Linkedin"><i class="fab fa-linkedin-in"></i></a>
      </div>
    </div>

    <div class="footer-col footer-links">
      <h3 class="footer-title">{% trans 'Quick Links' %}</h3>
      <ul class="footer-menu">
        <li>
          <a href="{% url 'whoweare:glance' %}">{% trans 'Who we are' %}</a>
        </li>
        <li>
          <a href="{% url 'products:products_list' %}">{% trans 'Products' %}</a>
        </li>
        <li>
          <a href="{% url 'services:services_list' %}">{% trans 'Services' %}</a>
        </li>
        <li>
          <a href="{% url 'brand_portal:brand_portal' %}">{% trans 'Brand Portal' %}</a>
        </li>
      </ul>
    </div>

    <div class="footer-col footer-menu2">
      <ul class="footer-menu-icons">
        <li>
          <a href="{% url 'news:news_list' %}"><i class="fas fa-chevron-right"></i> {% trans 'News' %}</a>
        </li>
        <li>
          <a href="{% url 'faq:faq' %}"><i class="fas fa-chevron-right"></i> {% trans 'FAQ' %}</a>
        </li>
        <li>
          <a href="{% url 'contact:contact' %}"><i class="fas fa-chevron-right"></i> {% trans 'Contact us' %}</a>
        </li>
        <li>
          <a href="{% url 'products:pds_sds' %}"><i class="fas fa-chevron-right"></i> {% trans 'PDS/SDS' %}</a>
        </li>
      </ul>
    </div>

    <div class="footer-col footer-info">
      <h3 class="footer-title">{% trans 'Stay in the Know' %}</h3>
      <p class="newsletter-text">
        {% blocktrans %} Be the first to hear about our latest news, updates,
        and exclusive insights. {% endblocktrans %}
      </p>
      <div>
        <form action="{% url 'contact:footer_email_submit' %}" method="post" class="newsletter-form">
          {% csrf_token %}
          <input type="email" name="email" placeholder="{% trans 'Enter your email' %}" required />
          <button type="submit" class="submit-btn" aria-label="{% trans 'SUBMIT' %}">
            <i class="fas fa-paper-plane"></i>
          </button>
        </form>
        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <li class="{{ message.tags }}">{{ message }}</li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>
    </div>

    <div class="footer-col footer-gallery">
      <h3 class="footer-title">{% trans 'Gallery' %}</h3>
      <div class="gallery-grid">
        <div class="gallery-item">
          <img loading="lazy" src="{% static 'images/footer-gallery-1.webp' %}" alt="Gallery Image" />
        </div>
        <div class="gallery-item">
          <img loading="lazy" src="{% static 'images/footer-gallery-2.webp' %}" alt="Gallery Image" />
        </div>
        <div class="gallery-item">
          <img loading="lazy" src="{% static 'images/footer-gallery-3.webp' %}" alt="Gallery Image" />
        </div>
        <div class="gallery-item">
          <img loading="lazy" src="{% static 'images/footer-gallery-4.webp' %}" alt="Gallery Image" />
        </div>
        <div class="gallery-item">
          <img loading="lazy" src="{% static 'images/footer-gallery-5.webp' %}" alt="Gallery Image" />
        </div>
        <div class="gallery-item">
          <img loading="lazy" src="{% static 'images/footer-gallery-6.webp' %}" alt="Gallery Image" />
        </div>
      </div>
    </div>
  </div>

  <div class="footer-bottom">
    <div class="footer-bottom-container">
      <p class="copyright">© TOMOIL 2025 | {% trans 'All Rights Reserved' %}</p>
      <div class="footer-links-bottom">
        <a href="#">{% trans 'Terms & Condition' %}</a>
        <span class="divider">|</span>
        <a href="#">{% trans 'Privacy Policy' %}</a>
        <span class="divider">|</span>
        <a href="#">{% trans 'Cookies' %}</a>
      </div>
    </div>
  </div>
</footer>

templates/components/navbar.html
{% load static %}
{% load i18n %}

<meta name="csrf-token" content="{{ csrf_token }}">

<nav class="">
  <div class="container">
    <div class="navbar">
      <div class="info">
        <div>
          <ul>
            <li>
              <i class="fa-solid fa-location-dot"></i>
              <p>{% trans 'Leitzstraße 45, 70469 Stuttgart, Germany' %}</p>
            </li>
            <li>
              <i class="fa-solid fa-envelope"></i>
               <a href="mailto:info&#64;tomoil&#46;de">info&#64;tomoil&#46;de</a>
            </li>
            <li>
              <i class="fa-solid fa-phone"></i>
              <a href="https://wa.me/4915221050103">{% trans 'Phone number' %}</a>
            </li>
          </ul>
        </div>
        <div class="info-book">
          <a class="button" href="{% url 'contact:contact' %}">{% trans 'Lets book a call' %}</a>
          <a class="button" href="{% url 'products:pds_sds' %}">{% trans 'PDS/SDS' %}</a>

          <div class="language-dropdown ">
            <button class="lang-dropdown-btn button">
              {% if LANGUAGE_CODE == 'en' %}EN{% elif LANGUAGE_CODE == 'de' %}DE{% elif LANGUAGE_CODE == 'es' %}ES{%
              elif LANGUAGE_CODE == 'fr' %}FR{% elif LANGUAGE_CODE == 'it' %}IT{% elif LANGUAGE_CODE == 'ca' %}汉语{% else
              %}EN{% endif %}
              <i class="fa-solid fa-angle-down"></i>
            </button>
            <div class="dropdown-content" id="languageDropdown">
              <button class="lang-option {% if LANGUAGE_CODE == 'en' %}active{% endif %}" data-lang="en">EN</button>
              <button class="lang-option {% if LANGUAGE_CODE == 'de' %}active{% endif %}" data-lang="de">DE</button>
              <button class="lang-option {% if LANGUAGE_CODE == 'es' %}active{% endif %}" data-lang="es">ES</button>
              <button class="lang-option {% if LANGUAGE_CODE == 'fr' %}active{% endif %}" data-lang="fr">FR</button>
              <button class="lang-option {% if LANGUAGE_CODE == 'it' %}active{% endif %}" data-lang="it">IT</button>
              <button class="lang-option {% if LANGUAGE_CODE == 'zh-hans' %}active{% endif %}"
                data-lang="zh-hans">汉语</button>
            </div>
          </div>

        </div>
      </div>
      <div class="nav-section">
        <a href="{% url 'contact:home' %}" class="logo">
          <img loading="lazy" src="{% static 'images/tomoil-logo1.svg' %}" alt="Tomoil" />
        </a>
        <div class="nav-list">
          <ul>
            <li class="dropdown">
              <a href="{% url 'whoweare:glance' %}">{% trans 'Who we Are' %}</a>
              <div class="dropdown-content">
                <a href="{% url 'whoweare:glance' %}">{% trans 'GLANCE' %}</a>
                <a href="{% url 'whoweare:vision_mission' %}">{% trans 'VISION & MISSION' %}</a>
                <a href="{% url 'whoweare:our_commitment_list' %}">{% trans 'OUR COMMITMENTS' %}</a>
              </div>
            </li>
            <li><a href="{% url 'products:products_list' %}">{% trans 'Products' %}</a></li>
            <li><a href="{% url 'services:services_list' %}">{% trans 'SERVICES' %}</a></li>
            <li><a href="{% url 'brand_portal:brand_portal' %}">{% trans 'Brand portal' %}</a></li>
            <li><a href="{% url 'news:news_list' %}">{% trans 'news' %}</a></li>
            <li><a href="{% url 'faq:faq' %}">{% trans 'faq' %}</a></li>
            <li><a href="{% url 'contact:contact' %}">{% trans 'Contact US' %}</a></li>
          </ul>
        </div>
        <div class="flex-buttons">

          <a class="search" aria-label="{% trans 'Search' %}" href="{% url 'search:search' %}"><i
              class="fa-solid fa-magnifying-glass"></i></a>

          <button class="hamburger" id="hamburger" aria-label="Mobile-Menu">
            <i class="fas fa-bars"></i>
          </button>

        </div>

      </div>
    </div>
  </div>
</nav>

<div class="mobile-menu" id="mobile-menu">
  <div class="mobile-nav-content">
    <ul class="mobile-nav-list">
      <li class="mobile-dropdown">
        <a href="{% url 'whoweare:glance' %}" class="mobile-dropdown-head">{% trans 'WHO WE ARE' %} <i
            class="fa-solid fa-chevron-right"></i></a>
        <div class="mobile-dropdown-content">
          <a href="{% url 'whoweare:glance' %}">{% trans 'GLANCE' %}</a>
          <a href="{% url 'whoweare:vision_mission' %}">{% trans 'VISION & MISSION' %}</a>
          <a href="{% url 'whoweare:our_commitment_list' %}">{% trans 'OUR COMMITMENTS' %}</a>
        </div>
      </li>
      <li class="mobile-nav-item"><a href="{% url 'products:products_list' %}">{% trans 'Products' %}</a></li>
      <li class="mobile-nav-item"><a href="{% url 'services:services_list' %}">{% trans 'SERVICES' %}</a></li>
      <li class="mobile-nav-item"><a href="{% url 'brand_portal:brand_portal' %}">{% trans 'BRAND PORTAL' %}</a></li>
      <li class="mobile-nav-item"><a href="{% url 'news:news_list' %}">{% trans 'NEWS' %}</a></li>
      <li class="mobile-nav-item"><a href="{% url 'faq:faq' %}">{% trans 'FAQ' %}</a></li>
      <li class="mobile-nav-item"><a href="{% url 'contact:contact' %}">{% trans 'CONTACT US' %}</a></li>
    </ul>
  </div>

  <div class="mobile-footer">
    <div class="mobile-buttons">
      <a class="mobile-btn" href="{% url 'contact:contact' %}">{% trans 'Lets book a call' %}</a>
      <a class="mobile-btn" href="{% url 'products:pds_sds' %}">{% trans 'PDS/SDS' %}</a>
    </div>

    <div class="mobile-contact">
      <div class="contact-item">
        <i class="fa-solid fa-location-dot"></i>
        <span>{% trans 'Leitzstraße 45, 70469 Stuttgart, Germany' %}</span>
      </div>
      <div class="contact-item">
        <i class="fa-solid fa-envelope"></i>
         <a href="mailto:info&#64;tomoil&#46;de">info&#64;tomoil&#46;de</a>
      </div>
      <div class="contact-item">
        <i class="fa-solid fa-phone"></i>
        <a href="tel:+4915781234567">{% trans 'Phone number' %}</a>
      </div>
    </div>

    <div class="mobile-languages">
      <button class="mobile lang-btn {% if LANGUAGE_CODE == 'en' %}active{% endif %}" data-lang="en">EN</button>
      <button class="mobile lang-btn {% if LANGUAGE_CODE == 'de' %}active{% endif %}" data-lang="de">DE</button>
      <button class="mobile lang-btn {% if LANGUAGE_CODE == 'es' %}active{% endif %}" data-lang="es">ES</button>
      <button class="mobile lang-btn {% if LANGUAGE_CODE == 'fr' %}active{% endif %}" data-lang="fr">FR</button>
      <button class="mobile lang-btn {% if LANGUAGE_CODE == 'it' %}active{% endif %}" data-lang="it">IT</button>
      <button class="mobile lang-btn {% if LANGUAGE_CODE == 'zh-hans' %}active{% endif %}"
        data-lang="zh-hans">汉语</button>
    </div>
  </div>
</div>

templates/components/page-header.html
{% load static %}
{% load i18n %}

<header class="placeholder-header page-header " {% if background_image %}style="background-image: url('{{ background_image.url }}')" {% endif %}>
    <div class="section-container">
            <div class="header-left">
                <div class="breadcrumb">
                    <a href="/">{% trans 'Home' %}</a>
                    {% if breadcrumb_title %}
                    <i class="fa-solid fa-angle-right"></i>
                    <a href="{{ breadcrumb_url|default:'/' }}">{{ breadcrumb_title }}</a>
                    {% endif %}
                </div>
                <div class="page-header-content">
                    <h1 class="page-title">{{ page_title}}</h1>
                    <p>{{ page_description }}</p>
                </div>
            </div>
            <div class="header-right">
                <a href="https://api.whatsapp.com/send?phone=4915221050103" class="header-whatsapp"
                    aria-label="{% trans 'Any questions? Ask in WhatsApp' %}" title="{% trans 'Any questions? Ask in WhatsApp' %}">
                    <i class="fab fa-whatsapp"></i>
                    <span>{% trans 'Any questions? Ask in WhatsApp' %}</span>
                </a>
           </div> 
    </div>

</header>
<a href="https://api.whatsapp.com/send?phone=4915221050103" class="fixed-whatsapp"
    aria-label="{% trans 'Any questions? Ask in WhatsApp' %}" title="{% trans 'Any questions? Ask in WhatsApp' %}">
    <i class="fab fa-whatsapp"></i>
</a>